/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3d029468-fb22-4299-929e-13ccfacacab6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lAmfhDqNp",
    "aws_user_pools_web_client_id": "4quc4la4bfvqjm1hvbk7v9jr30",
   
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "myapp808bb07e909940be81f6fb34caecfbbbe5d9e-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

export default awsmobile;
